SELECT P.PRODUCT_CODE, (P.PRICE * S.AMOUNT) AS SALES
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) S
LEFT JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC 