SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT I.USER_ID) / MAX(I.TOTAL_CNT), 1) AS PUCHASED_RATIO
FROM (
    SELECT USER_ID, 
        (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS TOTAL_CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC